
package vn.chodientu.component.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendMTPortType", targetNamespace = "http://sms.neo")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendMTPortType {


    /**
     * 
     * @param rtype
     * @param timeend
     * @param password
     * @param receiver
     * @param repeat
     * @param brandname
     * @param timestart
     * @param loaisp
     * @param content
     * @param timesend
     * @param username
     * @param target
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:sendMessage")
    @WebResult(targetNamespace = "http://sms.neo")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://sms.neo", className = "neo.sms.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://sms.neo", className = "neo.sms.SendMessageResponse")
    public String sendMessage(
        @WebParam(name = "username", targetNamespace = "http://sms.neo")
        String username,
        @WebParam(name = "password", targetNamespace = "http://sms.neo")
        String password,
        @WebParam(name = "receiver", targetNamespace = "http://sms.neo")
        String receiver,
        @WebParam(name = "content", targetNamespace = "http://sms.neo")
        String content,
        @WebParam(name = "repeat", targetNamespace = "http://sms.neo")
        Integer repeat,
        @WebParam(name = "rtype", targetNamespace = "http://sms.neo")
        Integer rtype,
        @WebParam(name = "loaisp", targetNamespace = "http://sms.neo")
        Integer loaisp,
        @WebParam(name = "brandname", targetNamespace = "http://sms.neo")
        String brandname,
        @WebParam(name = "timestart", targetNamespace = "http://sms.neo")
        String timestart,
        @WebParam(name = "timeend", targetNamespace = "http://sms.neo")
        String timeend,
        @WebParam(name = "timesend", targetNamespace = "http://sms.neo")
        String timesend,
        @WebParam(name = "target", targetNamespace = "http://sms.neo")
        String target);

    /**
     * 
     * @param password
     * @param receiver
     * @param content
     * @param username
     * @param target
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:sendFromServiceNumber")
    @WebResult(targetNamespace = "http://sms.neo")
    @RequestWrapper(localName = "sendFromServiceNumber", targetNamespace = "http://sms.neo", className = "neo.sms.SendFromServiceNumber")
    @ResponseWrapper(localName = "sendFromServiceNumberResponse", targetNamespace = "http://sms.neo", className = "neo.sms.SendFromServiceNumberResponse")
    public String sendFromServiceNumber(
        @WebParam(name = "username", targetNamespace = "http://sms.neo")
        String username,
        @WebParam(name = "password", targetNamespace = "http://sms.neo")
        String password,
        @WebParam(name = "receiver", targetNamespace = "http://sms.neo")
        String receiver,
        @WebParam(name = "content", targetNamespace = "http://sms.neo")
        String content,
        @WebParam(name = "target", targetNamespace = "http://sms.neo")
        String target);

    /**
     * 
     * @param password
     * @param receiver
     * @param brandname
     * @param content
     * @param username
     * @param target
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:sendFromBrandname")
    @WebResult(targetNamespace = "http://sms.neo")
    @RequestWrapper(localName = "sendFromBrandname", targetNamespace = "http://sms.neo", className = "neo.sms.SendFromBrandname")
    @ResponseWrapper(localName = "sendFromBrandnameResponse", targetNamespace = "http://sms.neo", className = "neo.sms.SendFromBrandnameResponse")
    public String sendFromBrandname(
        @WebParam(name = "username", targetNamespace = "http://sms.neo")
        String username,
        @WebParam(name = "password", targetNamespace = "http://sms.neo")
        String password,
        @WebParam(name = "receiver", targetNamespace = "http://sms.neo")
        String receiver,
        @WebParam(name = "brandname", targetNamespace = "http://sms.neo")
        String brandname,
        @WebParam(name = "content", targetNamespace = "http://sms.neo")
        String content,
        @WebParam(name = "target", targetNamespace = "http://sms.neo")
        String target);

    /**
     * 
     * @param password
     * @param cardSerial
     * @param cardCode
     * @param issure
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:useCard")
    @WebResult(targetNamespace = "http://sms.neo")
    @RequestWrapper(localName = "useCard", targetNamespace = "http://sms.neo", className = "neo.sms.UseCard")
    @ResponseWrapper(localName = "useCardResponse", targetNamespace = "http://sms.neo", className = "neo.sms.UseCardResponse")
    public String useCard(
        @WebParam(name = "username", targetNamespace = "http://sms.neo")
        String username,
        @WebParam(name = "password", targetNamespace = "http://sms.neo")
        String password,
        @WebParam(name = "issure", targetNamespace = "http://sms.neo")
        String issure,
        @WebParam(name = "cardCode", targetNamespace = "http://sms.neo")
        String cardCode,
        @WebParam(name = "cardSerial", targetNamespace = "http://sms.neo")
        String cardSerial);

    /**
     * 
     * @param password
     * @param receiver
     * @param brandname
     * @param loaisp
     * @param content
     * @param username
     * @param target
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:sendSMS")
    @WebResult(targetNamespace = "http://sms.neo")
    @RequestWrapper(localName = "sendSMS", targetNamespace = "http://sms.neo", className = "neo.sms.SendSMS")
    @ResponseWrapper(localName = "sendSMSResponse", targetNamespace = "http://sms.neo", className = "neo.sms.SendSMSResponse")
    public String sendSMS(
        @WebParam(name = "username", targetNamespace = "http://sms.neo")
        String username,
        @WebParam(name = "password", targetNamespace = "http://sms.neo")
        String password,
        @WebParam(name = "receiver", targetNamespace = "http://sms.neo")
        String receiver,
        @WebParam(name = "content", targetNamespace = "http://sms.neo")
        String content,
        @WebParam(name = "loaisp", targetNamespace = "http://sms.neo")
        Integer loaisp,
        @WebParam(name = "brandname", targetNamespace = "http://sms.neo")
        String brandname,
        @WebParam(name = "target", targetNamespace = "http://sms.neo")
        String target);

}
